"use client"

import type React from "react"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Progress } from "@/components/ui/progress"
import { Badge } from "@/components/ui/badge"
import { Upload, FileText, CheckCircle, AlertCircle, TrendingUp } from "lucide-react"

interface AnalysisResult {
  score: number
  strengths: string[]
  improvements: string[]
  recommendations: string[]
  analysis_date?: string
}

interface ResumeAnalyzerProps {
  studentId: string
  onComplete?: (score: number) => void
}

export default function ResumeAnalyzer({ studentId, onComplete }: ResumeAnalyzerProps) {
  const [file, setFile] = useState<File | null>(null)
  const [analyzing, setAnalyzing] = useState(false)
  const [result, setResult] = useState<AnalysisResult | null>(null)

  const handleFileSelect = (event: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFile = event.target.files?.[0]
    if (selectedFile) {
      setFile(selectedFile)
      setResult(null)
    }
  }

  const downloadDetailedReport = () => {
    if (!result) return

    // Create detailed report content
    const reportContent = `
RESUME ANALYSIS DETAILED REPORT
================================
Generated: ${new Date().toLocaleString()}

OVERALL SCORE: ${result.score}/100
${getScoreText(result.score)}

STRENGTHS:
${result.strengths.map((s, i) => `${i + 1}. ${s}`).join('\n')}

AREAS FOR IMPROVEMENT:
${result.improvements.map((s, i) => `${i + 1}. ${s}`).join('\n')}

RECOMMENDATIONS:
${result.recommendations.map((s, i) => `${i + 1}. ${s}`).join('\n')}

SCORE BREAKDOWN:
- Contact Information & Professional Summary
- Work Experience & Achievements
- Education & Certifications
- Skills & Keywords Optimization
- Formatting & ATS Compatibility

NEXT STEPS:
1. Address the improvements listed above
2. Implement the recommendations
3. Re-upload your updated resume for a new analysis
4. Track your progress over time

================================
Report generated by Cohort Placement System
    `.trim()

    // Create and download the file
    const blob = new Blob([reportContent], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `Resume_Analysis_Report_${new Date().toISOString().split('T')[0]}.txt`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }

  const getScoreText = (score: number): string => {
    if (score >= 90) return '🌟 Excellent! Your resume is highly competitive.'
    if (score >= 75) return '✅ Good! Minor improvements will make it great.'
    if (score >= 60) return '📈 Average. Focus on the improvements suggested.'
    if (score >= 40) return '⚠️ Needs Work. Follow the recommendations carefully.'
    return '❌ Significant improvements needed. Start with the basics.'
  }

  const analyzeResume = async () => {
    if (!file) return

    setAnalyzing(true)

    try {
      const formData = new FormData()
      formData.append('file', file)
      formData.append('studentId', studentId) // Use the passed studentId prop

      const response = await fetch('/api/resume/analyze', {
        method: 'POST',
        body: formData,
      })

      const data = await response.json()

      if (!response.ok) {
        // Handle specific error messages from the API
        const errorMessage = data.message || data.error || 'Analysis failed'
        const suggestion = data.suggestion || ''
        
        setResult({
          score: 0,
          strengths: [],
          improvements: [
            '❌ PDF Analysis Failed',
            errorMessage,
            suggestion ? `💡 Suggestion: ${suggestion}` : ''
          ].filter(Boolean),
          recommendations: [
            '🔄 Try re-saving your PDF from Word/Google Docs',
            '📄 Ensure the PDF is not password-protected',
            '🖼️ Make sure the PDF contains actual text (not just images)',
            '✅ Use a different PDF file if this one is corrupted'
          ],
        })
        
        setAnalyzing(false)
        return
      }

      if (data.success && data.analysis) {
        setResult({
          score: data.analysis.score,
          strengths: data.analysis.strengths,
          improvements: data.analysis.improvements,
          recommendations: data.analysis.recommendations,
        })
        
        // Callback to refresh dashboard
        if (onComplete) {
          onComplete(data.analysis.score)
        }
      } else {
        throw new Error(data.error || 'Analysis failed')
      }
    } catch (error) {
      console.error('Failed to analyze resume:', error)
      
      // Fallback to mock analysis
      const score = Math.floor(Math.random() * 50) + 40

      setResult({
        score,
        strengths: ['Contact information present'],
        improvements: ['Analysis failed. Please try again later.'],
        recommendations: ['Check your internet connection', 'Ensure the PDF is not corrupted'],
      })
    } finally {
      setAnalyzing(false)
    }
  }

  const getScoreColor = (score: number) => {
    if (score >= 80) return "text-green-500"
    if (score >= 60) return "text-yellow-500"
    return "text-red-500"
  }

  const getScoreBadge = (score: number) => {
    if (score >= 80) return <Badge className="bg-green-500/10 text-green-500 border-green-500/20">Excellent</Badge>
    if (score >= 60) return <Badge className="bg-yellow-500/10 text-yellow-500 border-yellow-500/20">Good</Badge>
    return <Badge className="bg-red-500/10 text-red-500 border-red-500/20">Needs Improvement</Badge>
  }

  if (analyzing) {
    return (
      <Card>
        <CardContent className="flex items-center justify-center py-12">
          <div className="text-center">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary mx-auto mb-4"></div>
            <p className="text-muted-foreground mb-2">Analyzing your resume...</p>
            <p className="text-sm text-muted-foreground">This may take a few moments</p>
          </div>
        </CardContent>
      </Card>
    )
  }

  if (result) {
    return (
      <div className="space-y-6">
        <Card>
          <CardHeader className="text-center">
            <CardTitle className="flex items-center justify-center">
              <TrendingUp className="h-6 w-6 mr-2 text-primary" />
              Resume Analysis Complete
            </CardTitle>
            <CardDescription>
              Analysis completed on {new Date().toLocaleDateString()}
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="text-center">
              <div className={`text-4xl font-bold mb-2 ${getScoreColor(result.score)}`}>{result.score}/100</div>
              <div className="mb-4">{getScoreBadge(result.score)}</div>
              <Progress value={result.score} className="max-w-md mx-auto" />
            </div>

            {/* Strengths */}
            {result.strengths.length > 0 && (
              <div className="space-y-3">
                <h4 className="font-semibold flex items-center text-green-600">
                  <CheckCircle className="h-4 w-4 mr-2" />
                  Strengths:
                </h4>
                {result.strengths.map((strength, index) => (
                  <div key={index} className="p-3 bg-green-50 dark:bg-green-900/20 rounded-lg">
                    <p className="text-sm text-foreground">✓ {strength}</p>
                  </div>
                ))}
              </div>
            )}

            {/* Improvements */}
            {result.improvements.length > 0 && (
              <div className="space-y-3">
                <h4 className="font-semibold flex items-center text-orange-600">
                  <AlertCircle className="h-4 w-4 mr-2" />
                  Areas for Improvement:
                </h4>
                {result.improvements.map((improvement, index) => (
                  <div key={index} className="p-3 bg-orange-50 dark:bg-orange-900/20 rounded-lg">
                    <p className="text-sm text-foreground">• {improvement}</p>
                  </div>
                ))}
              </div>
            )}

            {/* Recommendations */}
            {result.recommendations.length > 0 && (
              <div className="space-y-3">
                <h4 className="font-semibold flex items-center text-blue-600">
                  <TrendingUp className="h-4 w-4 mr-2" />
                  Recommendations:
                </h4>
                {result.recommendations.map((recommendation, index) => (
                  <div key={index} className="p-3 bg-blue-50 dark:bg-blue-900/20 rounded-lg">
                    <p className="text-sm text-foreground">→ {recommendation}</p>
                  </div>
                ))}
              </div>
            )}

            <div className="flex gap-3">
              <Button
                onClick={() => {
                  setFile(null)
                  setResult(null)
                }}
                variant="outline"
                className="flex-1"
              >
                Analyze Another Resume
              </Button>
              <Button 
                onClick={downloadDetailedReport}
                className="flex-1"
              >
                Download Detailed Report
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* Improvement Tips */}
        <Card>
          <CardHeader>
            <CardTitle>Resume Improvement Tips</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid md:grid-cols-2 gap-4">
              <div className="space-y-3">
                <h5 className="font-medium text-foreground">Content Tips:</h5>
                <ul className="space-y-2 text-sm text-muted-foreground">
                  <li>• Use action verbs to start bullet points</li>
                  <li>• Quantify achievements with numbers</li>
                  <li>• Tailor content to job requirements</li>
                  <li>• Include relevant technical skills</li>
                </ul>
              </div>
              <div className="space-y-3">
                <h5 className="font-medium text-foreground">Format Tips:</h5>
                <ul className="space-y-2 text-sm text-muted-foreground">
                  <li>• Keep it to 1-2 pages maximum</li>
                  <li>• Use consistent formatting</li>
                  <li>• Choose professional fonts</li>
                  <li>• Ensure proper spacing and margins</li>
                </ul>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    )
  }

  return (
    <Card>
      <CardHeader className="text-center">
        <CardTitle className="flex items-center justify-center">
          <FileText className="h-6 w-6 mr-2 text-primary" />
          Resume Analyzer
        </CardTitle>
        <CardDescription>Upload your resume to get detailed feedback and improvement suggestions</CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        <div className="border-2 border-dashed border-border rounded-lg p-8 text-center">
          {file ? (
            <div className="space-y-4">
              <CheckCircle className="h-12 w-12 text-green-500 mx-auto" />
              <div>
                <p className="font-medium text-foreground">{file.name}</p>
                <p className="text-sm text-muted-foreground">{(file.size / 1024 / 1024).toFixed(2)} MB</p>
              </div>
              <Button onClick={analyzeResume} className="w-full" size="lg">
                Analyze Resume
              </Button>
            </div>
          ) : (
            <div className="space-y-4">
              <Upload className="h-12 w-12 text-muted-foreground mx-auto" />
              <div>
                <p className="text-lg font-medium text-foreground">Upload Your Resume</p>
                <p className="text-sm text-muted-foreground">Supports PDF, DOC, and DOCX files up to 10MB</p>
              </div>
              <div>
                <input
                  type="file"
                  accept=".pdf,.doc,.docx"
                  onChange={handleFileSelect}
                  className="hidden"
                  id="resume-upload"
                />
                <label htmlFor="resume-upload">
                  <Button asChild size="lg">
                    <span>Choose File</span>
                  </Button>
                </label>
              </div>
            </div>
          )}
        </div>

        <div className="grid md:grid-cols-3 gap-4 text-center">
          <div className="p-4 bg-muted/50 rounded-lg">
            <div className="text-2xl font-bold text-foreground">AI-Powered</div>
            <div className="text-sm text-muted-foreground">Analysis</div>
          </div>
          <div className="p-4 bg-muted/50 rounded-lg">
            <div className="text-2xl font-bold text-foreground">Instant</div>
            <div className="text-sm text-muted-foreground">Feedback</div>
          </div>
          <div className="p-4 bg-muted/50 rounded-lg">
            <div className="text-2xl font-bold text-foreground">Actionable</div>
            <div className="text-sm text-muted-foreground">Tips</div>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}
